name: Auto Export CSV

on:
  schedule:
    - cron: '0 0 */90 * *'
  workflow_dispatch:

jobs:
  export_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Export CSV
      run: |
        node scripts/export_csv.js
